// Interface-logic tests, not a browser or visual-layout test.
const fs=require('fs'),vm=require('vm'),assert=require('assert');
const html=fs.readFileSync(__dirname+'/index.html','utf8');
const nodes=new Map();const data=new Map();let storageBlocked=false;let alerts=[];
function node(id){if(!nodes.has(id))nodes.set(id,{id,value:'',innerHTML:'',textContent:'',style:{},hidden:false,open:false,attrs:{},setAttribute(k,v){this.attrs[k]=v;if(k==='open')this.open=true},removeAttribute(k){delete this.attrs[k];if(k==='open')this.open=false},showModal(){this.open=true},close(){this.open=false},querySelector:()=>null,querySelectorAll:()=>[],insertAdjacentHTML(_p,t){this.innerHTML+=t},append(){},appendChild(){},prepend(){},focus(){},setSelectionRange(){}});return nodes.get(id)}
const ctx={console,URL,AbortController,Set,Map,Number,Date,JSON,Array,Error,Promise,document:{getElementById:node,querySelector:()=>null,querySelectorAll:()=>[],addEventListener:()=>{},activeElement:null,hidden:false,createElement:()=>({style:{},appendChild(){},querySelector:()=>({appendChild(){},isConnected:true}),querySelectorAll:()=>[]})},localStorage:{getItem:k=>{if(storageBlocked)throw Error();return data.get(k)||null},setItem:(k,v)=>{if(storageBlocked)throw Error();data.set(k,v)},removeItem:k=>data.delete(k)},alert:x=>alerts.push(x),location:{pathname:'/'},history:{pushState:(_a,_b,path)=>ctx.location.pathname=path,replaceState:(_a,_b,path)=>ctx.location.pathname=path},window:{},setTimeout:()=>1,clearTimeout:()=>{},setInterval:()=>1,fetch:async()=>({ok:true,json:async()=>({data:[],sources:[],status:'UNAVAILABLE',authenticated:false})})};
vm.createContext(ctx);vm.runInContext(html.split('<script>')[1].split('</script>')[0],ctx);
let count=0;function check(label,fn){fn();count++;console.log('PASS '+label)}
check('malformed local storage cannot crash page',()=>{data.set('vantix_watch','{bad');assert.equal(vm.runInContext("saved('vantix_watch').length",ctx),0)});
check('non-array local storage is discarded',()=>{data.set('vantix_watch','{}');assert.equal(vm.runInContext("saved('vantix_watch').length",ctx),0)});
check('watchlist injection rejected',()=>{data.set('vantix_watch',JSON.stringify(["');alert(1);//",'BTC']));assert.equal(vm.runInContext("saved('vantix_watch').join(',')",ctx),'BTC')});
check('corrupted holdings rejected',()=>{data.set('vantix_portfolio',JSON.stringify([{symbol:'BTC',qty:-1},{symbol:'ETH',qty:'<img>'},{symbol:'SOL',qty:2}]));assert.equal(vm.runInContext("saved('vantix_portfolio').length",ctx),1)});
check('storage unavailable handled',()=>{storageBlocked=true;assert.equal(vm.runInContext("saved('vantix_watch').length",ctx),0);assert.equal(vm.runInContext("storageSet('x','y')",ctx),false);storageBlocked=false});
check('numeric formatting handles invalid values',()=>{assert.equal(vm.runInContext('money(Infinity)',ctx),'—');assert.equal(vm.runInContext("money('wrong')",ctx),'—')});
check('unsafe URLs rejected',()=>assert.equal(vm.runInContext("safeLink('javascript:alert(1)')",ctx),''));
check('negative portfolio quantities not saved',()=>{node('portSymbol').value='BTC';node('portQty').value='-4';const old=data.get('vantix_portfolio');vm.runInContext('addHolding()',ctx);assert.equal(data.get('vantix_portfolio'),old)});
check('nonfinite alert thresholds not saved',()=>{node('alertSymbol').value='BTC';node('alertPrice').value='Infinity';vm.runInContext('addAlert()',ctx);assert.equal(data.has('vantix_alerts'),false)});
check('quotes no longer imply USD for USDT',()=>assert(!vm.runInContext('money(123)',ctx).includes('$')));
check('AI response identifies source search',()=>{node('q').value='inflation';vm.runInContext('searchSources()',ctx);assert(node('chat').innerHTML.includes('Source search · no AI interpretation'))});
check('watchlist markup has no injected dynamic script',()=>{ctx.location.pathname='/watchlist';vm.runInContext('render()',ctx);assert(!node('page').innerHTML.includes("removeWatch('"));assert(node('page').innerHTML.includes('savedRows'))});
for(const route of ['/','/ask','/markets','/crypto','/trending','/flows','/stocks','/forex','/commodities','/economy','/news','/feed','/radar','/shield','/watchlist','/alerts','/research','/copilot','/sectors','/portfolio','/account','/admin','/reset-password','/privacy','/terms']){check('render logic '+route,()=>{ctx.location.pathname=route;node('countrySelect').value='GBR';vm.runInContext('render()',ctx);assert(node('page').innerHTML.includes('<h1>'))})}
console.log(count+' interface-logic checks passed (no browser rendering).');
check('tiny token prices retain significant digits',()=>{assert.equal(vm.runInContext('tokenPrice(0.000000012345)',ctx),'1.2345e-8');assert.equal(vm.runInContext('tokenPrice(0)',ctx),'0');assert.equal(vm.runInContext('tokenPrice(null)',ctx),'—')});
check('risk ratios are unsigned and invalid evidence stays unknown',()=>{assert.equal(vm.runInContext('ratioPct(0.25)',ctx),'25.00%');assert.equal(vm.runInContext('ratioPct(0)',ctx),'0.00%');assert.equal(vm.runInContext('ratioPct(null)',ctx),'Unknown');assert.equal(vm.runInContext('ratioPct(2)',ctx),'Unknown')});
check('failed GMGN request never claims retrieval',()=>{assert.equal(vm.runInContext("gmgnResult({status:'rejected'},'Fresh').summary",ctx),'Fresh: unavailable.')});
check('stale GMGN observations remain explicitly stale',()=>{assert(vm.runInContext("gmgnResult({status:'fulfilled',value:{status:'STALE',data:[],retrieved_at:'2026-09-18'}},'Fresh').html",ctx).includes('stale cached results'))});
check('trending separates Popular and New Pairs into columns',()=>{ctx.location.pathname='/trending';vm.runInContext('render()',ctx);assert(node('page').innerHTML.includes('gmgnColumns'));assert(node('page').innerHTML.includes('<h2>Popular</h2>'));assert(node('page').innerHTML.includes('<h2>New Pairs</h2>'));assert(node('page').innerHTML.includes('Chain filter'))});
check('GMGN filters keep unknown fields until a minimum is chosen',()=>{node('gmgnSearch').value='';node('gmgnMinLiquidity').value='';node('gmgnMinMarketCap').value='';node('gmgnMaxRisk').value='';node('gmgnSort').value='rank';ctx.filterRows=[{symbol:'NEW',rank:2},{symbol:'OLD',rank:1,liquidity:100}];assert.equal(vm.runInContext('gmgnFilterRows(filterRows).length',ctx),2);node('gmgnMinLiquidity').value='50';assert.equal(vm.runInContext('gmgnFilterRows(filterRows).length',ctx),1)});
check('GMGN search, risk and sort filters work locally',()=>{node('gmgnSearch').value='moon';node('gmgnMinLiquidity').value='';node('gmgnMinMarketCap').value='';node('gmgnMaxRisk').value='30';node('gmgnSort').value='volume';ctx.filterRows=[{symbol:'MOON',name:'Moon coin',rug_ratio:.2,volume:10},{symbol:'MOON2',name:'Moon two',rug_ratio:.1,volume:20},{symbol:'SAFE',name:'Other',rug_ratio:.1,volume:30},{symbol:'MOONX',name:'Unknown risk',volume:40}];const rows=vm.runInContext('gmgnFilterRows(filterRows)',ctx);assert.equal(rows.length,2);assert.equal(rows[0].symbol,'MOON2');vm.runInContext('resetGmgnFilters()',ctx);assert.equal(node('gmgnSearch').value,'');assert.equal(node('gmgnSort').value,'rank')});
check('Bybit documented spot snapshot is accepted and stale data rejected',()=>{const now=Date.now();ctx.ticker={topic:'tickers.BTCUSDT',type:'snapshot',ts:now,data:{symbol:'BTCUSDT',lastPrice:'60000',price24hPcnt:'0.02',turnover24h:'10000'}};assert.equal(vm.runInContext('acceptBybitMessage(ticker)',ctx),true);ctx.ticker.ts=now-60000;assert.equal(vm.runInContext('acceptBybitMessage(ticker)',ctx),false)});
check('Coinbase documented ticker is accepted as a separate USD quote',()=>{const now=new Date().toISOString();ctx.cbTicker={type:'ticker',product_id:'BTC-USD',price:'60000',open_24h:'59000',volume_24h:'100',time:now};assert.equal(vm.runInContext('acceptCoinbaseMessage(cbTicker)',ctx),true);assert.equal(vm.runInContext("liveQuotes.get('coinbase/BTC').quote",ctx),'USD');node('exchangeComparison').innerHTML='';vm.runInContext('paintExchangeComparison()',ctx);assert(node('exchangeComparison').innerHTML.includes('Coinbase · USD'))});
check('Coinbase rejects stale and unsupported product observations',()=>{ctx.cbTicker.time=new Date(Date.now()-60000).toISOString();assert.equal(vm.runInContext('acceptCoinbaseMessage(cbTicker)',ctx),false);ctx.cbTicker={...ctx.cbTicker,product_id:'BNB-USD',time:new Date().toISOString()};assert.equal(vm.runInContext('acceptCoinbaseMessage(cbTicker)',ctx),false)});
check('all market pages expose bounded chart choices',()=>{ctx.location.pathname='/stocks';vm.runInContext("setChartSymbol('NASDAQ:NVDA')",ctx);assert.equal(vm.runInContext("chartDefaults['/stocks']",ctx),'NASDAQ:NVDA');vm.runInContext("setChartSymbol('BAD:SYMBOL')",ctx);assert.equal(vm.runInContext("chartDefaults['/stocks']",ctx),'NASDAQ:NVDA');assert(vm.runInContext("chartChoices['/forex'].includes('FX:USDJPY')",ctx));assert(vm.runInContext("chartChoices['/crypto'].includes('BINANCE:ETHUSDT')",ctx));ctx.location.pathname='/commodities';vm.runInContext('render()',ctx);assert(node('page').innerHTML.includes('Metals and energy'))});
check('chart workspace supports validated timeframes and four-chart maximum',()=>{ctx.location.pathname='/stocks';vm.runInContext("setChartInterval('D')",ctx);assert.equal(vm.runInContext('chartInterval',ctx),'D');vm.runInContext("setChartInterval('INVALID')",ctx);assert.equal(vm.runInContext('chartInterval',ctx),'D');vm.runInContext("chartOpen['/stocks']=['NASDAQ:AAPL','NASDAQ:MSFT','NASDAQ:NVDA','NASDAQ:AMZN']",ctx);node('chartAsset').value='NASDAQ:TSLA';alerts=[];vm.runInContext('addChart()',ctx);assert.equal(vm.runInContext("chartOpen['/stocks'].length",ctx),4);assert(alerts[0].includes('four charts'))});
check('Market Copilot redirects to the single Ask VANTIX experience',()=>{ctx.location.pathname='/copilot';vm.runInContext('render()',ctx);assert.equal(ctx.location.pathname,'/ask');assert(node('page').innerHTML.includes('Ask VANTIX'))});
check('top search uses its own input and stays empty until typing',()=>{ctx.location.pathname='/';node('globalSearchInput').value='';vm.runInContext('runGlobalSearch()',ctx);assert.equal(node('globalSearchResults').hidden,true);node('globalSearchInput').value='bitcoin';vm.runInContext('runGlobalSearch()',ctx);assert.equal(ctx.location.pathname,'/');assert.equal(node('globalSearchResults').hidden,false);assert(node('globalSearchResults').innerHTML.includes('Bitcoin'));assert(!node('globalSearchResults').innerHTML.includes('sendAI'))});
check('sidebar restores world news, market chat and alerts',()=>{assert(node('nav').innerHTML.includes('World News'));assert(node('nav').innerHTML.includes('Market Chat'));assert(node('nav').innerHTML.includes('Alerts'));assert(node('nav').innerHTML.includes('Whale & Fund Flows'))});
check('homepage leads with ranked market-moving news',()=>{ctx.location.pathname='/';vm.runInContext("newsData=[{title:'Central bank rate decision lifts dollar',source:'Fixture',category:'finance',link:'https://example.com',published:'now',status:'INDEXED'}]",ctx);vm.runInContext('render()',ctx);assert(node('page').innerHTML.includes('Market Impact Now'));assert(node('page').innerHTML.includes('impactLevel high'));assert(node('page').innerHTML.includes('FX &amp; rates'));assert(node('page').innerHTML.includes('Latest financial news'))});
check('news page offers financial market and impact filters',()=>{ctx.location.pathname='/news';vm.runInContext('render()',ctx);assert(node('page').innerHTML.includes('Market-Moving News'));assert(node('page').innerHTML.includes('Financial markets'));assert(node('page').innerHTML.includes('Market Impact'))});
check('radar rows open details and lead to charts',()=>{ctx.location.pathname='/radar';vm.runInContext("marketData=[{symbol:'BTC',price:10,change:2,volume:100,quote:'USDT',source:'fixture',status:'LIVE',updated:'now'},{symbol:'SOL',price:2,change:8,volume:300,quote:'USDT',source:'fixture',status:'LIVE',updated:'now'}]",ctx);vm.runInContext('render()',ctx);assert.equal(vm.runInContext('radarMetrics().length',ctx),2);assert(node('page').innerHTML.includes('MINIMUM SCORE'));assert(node('radarResults').innerHTML.includes('View details'));assert(node('radarResults').innerHTML.includes('Open live chart'));assert(node('radarResults').innerHTML.includes('Check contract in Shield'));assert(node('radarResults').innerHTML.includes('Add to Watchlist'))});
check('market clicks open internal charts instead of AI',()=>{ctx.location.pathname='/';vm.runInContext("assetAction('BTC')",ctx);assert.equal(ctx.location.pathname,'/crypto');assert.equal(vm.runInContext("chartOpen['/crypto'][0]",ctx),'BINANCE:BTCUSDT');assert(!node('page').innerHTML.includes('Your question'))});
check('stock picker updates the internal chart',()=>{ctx.location.pathname='/stocks';vm.runInContext("openChartSymbol('NASDAQ:NVDA')",ctx);assert.equal(ctx.location.pathname,'/stocks');assert.equal(vm.runInContext("chartOpen['/stocks'][0]",ctx),'NASDAQ:NVDA');assert(node('page').innerHTML.includes('Choose an instrument to open its chart inside VANTIX'))});
check('trending coin click opens its chart without AI links',()=>{node('gmgnSearch').value='';node('gmgnMinLiquidity').value='';node('gmgnMinMarketCap').value='';node('gmgnMaxRisk').value='';node('gmgnSort').value='rank';vm.runInContext("gmgnData.trending=[{symbol:'BTC',name:'Bitcoin',chain:'sol',price_change:4,volume:1000,liquidity:500,market_cap:5000,address:'fixtureAddress'}]",ctx);vm.runInContext("showCoinDetail('trending',0)",ctx);assert.equal(node('coinDialog').open,true);assert(node('coinDialog').innerHTML.includes('coinDetailChart'));assert(!node('coinDialog').innerHTML.includes('Ask VANTIX'));assert(!node('coinDialog').innerHTML.includes('target=\"_blank\"'))});
check('token pairs open an embedded chart inside VANTIX',()=>{vm.runInContext("tokenPairData=[{title:'TOKEN/USDC',chain:'solana',pair:'ABCDEF123456',price:1,liquidity:2}]",ctx);vm.runInContext('showPairChart(0)',ctx);assert.equal(node('pairDialog').open,true);assert(node('pairChartHost').innerHTML.includes('dexscreener.com/solana/ABCDEF123456'));assert(!node('pairDialog').innerHTML.includes('target=\"_blank\"'))});
check('market chat includes rooms, members and feed filters',()=>{ctx.location.pathname='/feed';vm.runInContext('render()',ctx);assert(node('page').innerHTML.includes('ACTIVE MEMBERS'));assert(node('page').innerHTML.includes('Global Markets'));assert(node('page').innerHTML.includes('Weather & Commodities'));assert(node('page').innerHTML.includes('Trending'));assert(node('page').innerHTML.includes('Following'))});

check('instrument filter matches names and handles no matches',()=>{ctx.location.pathname='/stocks';node('chartSearch').value='nvidia';vm.runInContext('filterChartInstruments()',ctx);assert(node('chartAsset').innerHTML.includes('NASDAQ:NVDA'));assert(!node('chartAsset').innerHTML.includes('NASDAQ:AAPL'));node('chartSearch').value='unlisted';vm.runInContext('filterChartInstruments()',ctx);assert(node('chartAsset').innerHTML.includes('No matching instrument'))});
check('chart style rejects unsupported values',()=>{node('chartStyle').value='2';vm.runInContext('applyChartStyle()',ctx);assert.equal(vm.runInContext('chartStyle',ctx),'2');node('chartStyle').value='bad';vm.runInContext('applyChartStyle()',ctx);assert.equal(vm.runInContext('chartStyle',ctx),'2')});
check('news preview retains record identity and escapes source content',()=>{ctx.article={title:'Bitcoin <img src=x onerror=alert(1)>',source:'Fixture',link:'javascript:alert(1)'};const id=vm.runInContext('newsRecordId(article)',ctx);vm.runInContext('newsData=[]',ctx);vm.runInContext('openNewsPreview('+id+')',ctx);assert(node('marketToolDialog').innerHTML.includes('&lt;img'));assert(!node('marketToolDialog').innerHTML.includes('javascript:'));assert(node('marketToolDialog').innerHTML.includes('Headline-only'));assert.equal(node('marketToolDialog').open,true)});
check('related news matches ticker words without substring false positives',()=>{vm.runInContext("newsData=[{title:'Bitcoin ETF inflows'},{title:'BTC market news'},{title:'A story about abcBTCxyz'}]",ctx);assert.equal(vm.runInContext("assetNews('BINANCE:BTCUSDT').length",ctx),2)});
check('saved instruments resolve to internal charts across asset classes',()=>{for(const [key,expected] of [['BTC','BINANCE:BTCUSDT'],['NVDA','NASDAQ:NVDA'],['EURUSD','FX:EURUSD'],['GOLD','TVC:GOLD']]){ctx.key=key;assert.equal(vm.runInContext('savedInstrument(key)',ctx),expected)}assert.equal(vm.runInContext("savedInstrument('UNKNOWN')",ctx),null)});
check('quick alerts reject nonfinite values before saving',()=>{vm.runInContext("showAssetTools('BINANCE:BTCUSDT','alerts')",ctx);node('quickAlertPrice').value='Infinity';vm.runInContext('saveAssetTool()',ctx);assert(node('quickSaveStatus').textContent.includes('positive finite'));const before=node('marketToolDialog').innerHTML;vm.runInContext("showAssetTools('NASDAQ:AAPL','alerts')",ctx);assert.equal(node('marketToolDialog').innerHTML,before)});
check('global news search opens previews rather than external pages or AI',()=>{vm.runInContext("newsData=[{title:'Bitcoin policy update',source:'Fixture',link:'https://example.com'}]",ctx);node('globalSearchInput').value='policy update';vm.runInContext('runGlobalSearch()',ctx);assert(node('globalSearchResults').innerHTML.includes('openNewsPreview'));assert(!node('globalSearchResults').innerHTML.includes('target='));assert(!node('globalSearchResults').innerHTML.includes('sendAI'))});
(async()=>{
 await new Promise(resolve=>setImmediate(resolve));
 const pending=[];ctx.fetch=async url=>new Promise(resolve=>pending.push({url,resolve}));
 node('gmgnChain').value='sol';node('gmgnInterval').value='5m';
 const first=vm.runInContext('loadGmgn()',ctx);
 node('gmgnChain').value='base';const second=vm.runInContext('loadGmgn()',ctx);
 const answer=(request,symbol)=>request.resolve({ok:true,json:async()=>({status:'PROVIDER_QUERY',data:[{symbol,chain:symbol,price:0.00000001}]})});
 pending.slice(2).forEach(r=>answer(r,'BASE'));await second;
 pending.slice(0,2).forEach(r=>answer(r,'SOL'));await first;
 check('late previous-chain responses cannot overwrite selected chain',()=>{assert(node('gmgnTrending').innerHTML.includes('BASE'));assert(!node('gmgnTrending').innerHTML.includes('SOL'));assert(node('gmgnStatus').textContent.startsWith('BASE'))});
 ctx.fetch=async()=>{throw Error('offline')};await vm.runInContext('loadGmgn()',ctx);
 check('both GMGN transport failures report unavailability',()=>{assert(!node('gmgnStatus').textContent.includes('retrieved'));assert(node('gmgnFresh').innerHTML.includes('unavailable'))});
 console.log(count+' interface-logic checks passed (including async regressions).');
})().catch(e=>{console.error(e);process.exitCode=1});
