// Interface-logic tests, not a browser or visual-layout test.
const fs=require('fs'),vm=require('vm'),assert=require('assert');
const html=fs.readFileSync(__dirname+'/index.html','utf8');
const nodes=new Map();const data=new Map();let storageBlocked=false;let alerts=[];
function node(id){if(!nodes.has(id))nodes.set(id,{id,value:'',innerHTML:'',textContent:'',style:{},querySelector:()=>null,querySelectorAll:()=>[],insertAdjacentHTML(_p,t){this.innerHTML+=t},append(){},prepend(){},focus(){},setSelectionRange(){}});return nodes.get(id)}
const ctx={console,URL,AbortController,Set,Map,Number,Date,JSON,Array,Error,Promise,document:{getElementById:node,querySelector:()=>null,querySelectorAll:()=>[],addEventListener:()=>{},activeElement:null,hidden:false,createElement:()=>({style:{},appendChild(){},querySelector:()=>({appendChild(){},isConnected:true}),querySelectorAll:()=>[]})},localStorage:{getItem:k=>{if(storageBlocked)throw Error();return data.get(k)||null},setItem:(k,v)=>{if(storageBlocked)throw Error();data.set(k,v)},removeItem:k=>data.delete(k)},alert:x=>alerts.push(x),location:{pathname:'/'},history:{pushState:(_a,_b,path)=>ctx.location.pathname=path,replaceState:(_a,_b,path)=>ctx.location.pathname=path},window:{},setTimeout:()=>1,clearTimeout:()=>{},setInterval:()=>1,fetch:async()=>({ok:true,json:async()=>({data:[],sources:[],status:'UNAVAILABLE',authenticated:false})})};
vm.createContext(ctx);vm.runInContext(html.split('<script>')[1].split('</script>')[0],ctx);
let count=0;function check(label,fn){fn();count++;console.log('PASS '+label)}
check('malformed local storage cannot crash page',()=>{data.set('vantix_watch','{bad');assert.equal(vm.runInContext("saved('vantix_watch').length",ctx),0)});
check('non-array local storage is discarded',()=>{data.set('vantix_watch','{}');assert.equal(vm.runInContext("saved('vantix_watch').length",ctx),0)});
check('watchlist injection rejected',()=>{data.set('vantix_watch',JSON.stringify(["');alert(1);//",'BTC']));assert.equal(vm.runInContext("saved('vantix_watch').join(',')",ctx),'BTC')});
check('corrupted holdings rejected',()=>{data.set('vantix_portfolio',JSON.stringify([{symbol:'BTC',qty:-1},{symbol:'ETH',qty:'<img>'},{symbol:'SOL',qty:2}]));assert.equal(vm.runInContext("saved('vantix_portfolio').length",ctx),1)});
check('storage unavailable handled',()=>{storageBlocked=true;assert.equal(vm.runInContext("saved('vantix_watch').length",ctx),0);assert.equal(vm.runInContext("storageSet('x','y')",ctx),false);storageBlocked=false});
check('numeric formatting handles invalid values',()=>{assert.equal(vm.runInContext('money(Infinity)',ctx),'—');assert.equal(vm.runInContext("money('wrong')",ctx),'—')});
check('unsafe URLs rejected',()=>assert.equal(vm.runInContext("safeLink('javascript:alert(1)')",ctx),''));
check('negative portfolio quantities not saved',()=>{node('portSymbol').value='BTC';node('portQty').value='-4';const old=data.get('vantix_portfolio');vm.runInContext('addHolding()',ctx);assert.equal(data.get('vantix_portfolio'),old)});
check('nonfinite alert thresholds not saved',()=>{node('alertSymbol').value='BTC';node('alertPrice').value='Infinity';vm.runInContext('addAlert()',ctx);assert.equal(data.has('vantix_alerts'),false)});
check('quotes no longer imply USD for USDT',()=>assert(!vm.runInContext('money(123)',ctx).includes('$')));
check('AI response identifies source search',()=>{node('q').value='inflation';vm.runInContext('searchSources()',ctx);assert(node('chat').innerHTML.includes('Source search · no AI interpretation'))});
check('watchlist markup has no injected dynamic script',()=>{ctx.location.pathname='/watchlist';vm.runInContext('render()',ctx);assert(!node('page').innerHTML.includes("removeWatch('"));assert(node('page').innerHTML.includes('savedRows'))});
for(const route of ['/','/ask','/markets','/crypto','/trending','/stocks','/forex','/commodities','/economy','/news','/feed','/radar','/shield','/watchlist','/alerts','/research','/copilot','/sectors','/portfolio','/account','/admin','/reset-password','/privacy','/terms']){check('render logic '+route,()=>{ctx.location.pathname=route;node('countrySelect').value='GBR';vm.runInContext('render()',ctx);assert(node('page').innerHTML.includes('<h1>'))})}
console.log(count+' interface-logic checks passed (no browser rendering).');
check('tiny token prices retain significant digits',()=>{assert.equal(vm.runInContext('tokenPrice(0.000000012345)',ctx),'1.2345e-8');assert.equal(vm.runInContext('tokenPrice(0)',ctx),'0');assert.equal(vm.runInContext('tokenPrice(null)',ctx),'—')});
check('risk ratios are unsigned and invalid evidence stays unknown',()=>{assert.equal(vm.runInContext('ratioPct(0.25)',ctx),'25.00%');assert.equal(vm.runInContext('ratioPct(0)',ctx),'0.00%');assert.equal(vm.runInContext('ratioPct(null)',ctx),'Unknown');assert.equal(vm.runInContext('ratioPct(2)',ctx),'Unknown')});
check('failed GMGN request never claims retrieval',()=>{assert.equal(vm.runInContext("gmgnResult({status:'rejected'},'Fresh').summary",ctx),'Fresh: unavailable.')});
check('stale GMGN observations remain explicitly stale',()=>{assert(vm.runInContext("gmgnResult({status:'fulfilled',value:{status:'STALE',data:[],retrieved_at:'2026-09-18'}},'Fresh').html",ctx).includes('stale cached results'))});
check('trending separates Popular and New Pairs into columns',()=>{ctx.location.pathname='/trending';vm.runInContext('render()',ctx);assert(node('page').innerHTML.includes('gmgnColumns'));assert(node('page').innerHTML.includes('<h2>Popular</h2>'));assert(node('page').innerHTML.includes('<h2>New Pairs</h2>'));assert(node('page').innerHTML.includes('Chain filter'))});
check('GMGN filters keep unknown fields until a minimum is chosen',()=>{node('gmgnSearch').value='';node('gmgnMinLiquidity').value='';node('gmgnMinMarketCap').value='';node('gmgnMaxRisk').value='';node('gmgnSort').value='rank';ctx.filterRows=[{symbol:'NEW',rank:2},{symbol:'OLD',rank:1,liquidity:100}];assert.equal(vm.runInContext('gmgnFilterRows(filterRows).length',ctx),2);node('gmgnMinLiquidity').value='50';assert.equal(vm.runInContext('gmgnFilterRows(filterRows).length',ctx),1)});
check('GMGN search, risk and sort filters work locally',()=>{node('gmgnSearch').value='moon';node('gmgnMinLiquidity').value='';node('gmgnMinMarketCap').value='';node('gmgnMaxRisk').value='30';node('gmgnSort').value='volume';ctx.filterRows=[{symbol:'MOON',name:'Moon coin',rug_ratio:.2,volume:10},{symbol:'MOON2',name:'Moon two',rug_ratio:.1,volume:20},{symbol:'SAFE',name:'Other',rug_ratio:.1,volume:30},{symbol:'MOONX',name:'Unknown risk',volume:40}];const rows=vm.runInContext('gmgnFilterRows(filterRows)',ctx);assert.equal(rows.length,2);assert.equal(rows[0].symbol,'MOON2');vm.runInContext('resetGmgnFilters()',ctx);assert.equal(node('gmgnSearch').value,'');assert.equal(node('gmgnSort').value,'rank')});
check('Bybit documented spot snapshot is accepted and stale data rejected',()=>{const now=Date.now();ctx.ticker={topic:'tickers.BTCUSDT',type:'snapshot',ts:now,data:{symbol:'BTCUSDT',lastPrice:'60000',price24hPcnt:'0.02',turnover24h:'10000'}};assert.equal(vm.runInContext('acceptBybitMessage(ticker)',ctx),true);ctx.ticker.ts=now-60000;assert.equal(vm.runInContext('acceptBybitMessage(ticker)',ctx),false)});
check('Coinbase documented ticker is accepted as a separate USD quote',()=>{const now=new Date().toISOString();ctx.cbTicker={type:'ticker',product_id:'BTC-USD',price:'60000',open_24h:'59000',volume_24h:'100',time:now};assert.equal(vm.runInContext('acceptCoinbaseMessage(cbTicker)',ctx),true);assert.equal(vm.runInContext("liveQuotes.get('coinbase/BTC').quote",ctx),'USD');node('exchangeComparison').innerHTML='';vm.runInContext('paintExchangeComparison()',ctx);assert(node('exchangeComparison').innerHTML.includes('Coinbase · USD'))});
check('Coinbase rejects stale and unsupported product observations',()=>{ctx.cbTicker.time=new Date(Date.now()-60000).toISOString();assert.equal(vm.runInContext('acceptCoinbaseMessage(cbTicker)',ctx),false);ctx.cbTicker={...ctx.cbTicker,product_id:'BNB-USD',time:new Date().toISOString()};assert.equal(vm.runInContext('acceptCoinbaseMessage(cbTicker)',ctx),false)});
check('all market pages expose bounded chart choices',()=>{ctx.location.pathname='/stocks';vm.runInContext("setChartSymbol('NASDAQ:NVDA')",ctx);assert.equal(vm.runInContext("chartDefaults['/stocks']",ctx),'NASDAQ:NVDA');vm.runInContext("setChartSymbol('BAD:SYMBOL')",ctx);assert.equal(vm.runInContext("chartDefaults['/stocks']",ctx),'NASDAQ:NVDA');assert(vm.runInContext("chartChoices['/forex'].includes('FX:USDJPY')",ctx));assert(vm.runInContext("chartChoices['/crypto'].includes('BINANCE:ETHUSDT')",ctx));ctx.location.pathname='/commodities';vm.runInContext('render()',ctx);assert(node('page').innerHTML.includes('Metals and energy'))});
check('chart workspace supports validated timeframes and four-chart maximum',()=>{ctx.location.pathname='/stocks';vm.runInContext("setChartInterval('D')",ctx);assert.equal(vm.runInContext('chartInterval',ctx),'D');vm.runInContext("setChartInterval('INVALID')",ctx);assert.equal(vm.runInContext('chartInterval',ctx),'D');vm.runInContext("chartOpen['/stocks']=['NASDAQ:AAPL','NASDAQ:MSFT','NASDAQ:NVDA','NASDAQ:AMZN']",ctx);node('chartAsset').value='NASDAQ:TSLA';alerts=[];vm.runInContext('addChart()',ctx);assert.equal(vm.runInContext("chartOpen['/stocks'].length",ctx),4);assert(alerts[0].includes('four charts'))});
check('Market Copilot redirects to the single Ask VANTIX experience',()=>{ctx.location.pathname='/copilot';vm.runInContext('render()',ctx);assert.equal(ctx.location.pathname,'/ask');assert(node('page').innerHTML.includes('Ask VANTIX'))});
check('community page includes feed filters and leaderboard',()=>{ctx.location.pathname='/feed';vm.runInContext('render()',ctx);assert(node('page').innerHTML.includes('LEADERBOARD'));assert(node('page').innerHTML.includes('Trending'));assert(node('page').innerHTML.includes('Following'))});
(async()=>{
 await new Promise(resolve=>setImmediate(resolve));
 const pending=[];ctx.fetch=async url=>new Promise(resolve=>pending.push({url,resolve}));
 node('gmgnChain').value='sol';node('gmgnInterval').value='5m';
 const first=vm.runInContext('loadGmgn()',ctx);
 node('gmgnChain').value='base';const second=vm.runInContext('loadGmgn()',ctx);
 const answer=(request,symbol)=>request.resolve({ok:true,json:async()=>({status:'PROVIDER_QUERY',data:[{symbol,chain:symbol,price:0.00000001}]})});
 pending.slice(2).forEach(r=>answer(r,'BASE'));await second;
 pending.slice(0,2).forEach(r=>answer(r,'SOL'));await first;
 check('late previous-chain responses cannot overwrite selected chain',()=>{assert(node('gmgnTrending').innerHTML.includes('BASE'));assert(!node('gmgnTrending').innerHTML.includes('SOL'));assert(node('gmgnStatus').textContent.startsWith('BASE'))});
 ctx.fetch=async()=>{throw Error('offline')};await vm.runInContext('loadGmgn()',ctx);
 check('both GMGN transport failures report unavailability',()=>{assert(!node('gmgnStatus').textContent.includes('retrieved'));assert(node('gmgnFresh').innerHTML.includes('unavailable'))});
 console.log(count+' interface-logic checks passed (including async regressions).');
})().catch(e=>{console.error(e);process.exitCode=1});
