'use strict';
const policyDocuments={
terms:{title:'Terms & conditions',intro:'Pre-launch draft · version 0.1 · 28 September 2026',body:`
<h2>1. Current service</h2><p>VIRTLINK is currently a concept preview of a professional social network. Profiles, investors, jobs, events and conversations are illustrative. Private test accounts and the member feed are connected. Posts published while signed in are saved and visible to signed-in members. Public registration remains closed. No proposal is delivered and no investment transaction is available. Do not rely on example information to make a financial decision.</p>
<h2>2. Operator and final terms</h2><p>The legal operator, business address, support contact, applicable jurisdiction and complaints process must be confirmed before public registration. This draft is not the final agreement for a live service and has not received legal approval.</p>
<h2>3. Using the preview</h2><p>Use fictional details only. Do not enter passwords, confidential business plans, identity documents, bank details or payment information. Do not impersonate others, introduce malicious code, attempt unauthorised access or use the service for unlawful activity.</p>
<h2>4. Networking and investment activity</h2><p>The intended service helps people discover and contact each other. VIRTLINK does not, through this preview, provide investment advice, hold client money, broker transactions, guarantee introductions or promise funding or returns. Whether future features require authorisation, approvals or other controls must be assessed before they open; calling a service “networking” does not determine its legal status.</p><p>Members must substantiate claims and disclose relevant conflicts. Investment promotions, fundraising distribution and transaction features will remain unavailable until the applicable legal requirements and permissions have been assessed. A verification label must never be presented as a guarantee that a person or investment is safe.</p>
<h2>5. Proposals and content</h2><p>You retain ownership of your material. Preview drafts remain in your browser session. No confidentiality agreement is created by writing a draft. Before live sharing opens, the final terms must define recipient permissions, platform processing rights, confidentiality limits and deletion arrangements. Share only material you own or have permission to use.</p>
<h2>6. Responsibility and liability — draft</h2><p>VIRTLINK does not guarantee another member’s statements, performance, financial capacity or a particular business outcome. Members must conduct their own checks and obtain appropriate independent advice before entering an agreement. VIRTLINK is not automatically a party to agreements made between members.</p><p>Any final limitation of liability must be fair, clear and lawful. Nothing in these proposed terms is intended to exclude liability for fraud or fraudulent misrepresentation, death or personal injury caused by negligence, or any responsibility or consumer right that cannot lawfully be excluded or restricted. This draft does not create blanket immunity for VIRTLINK or its operator.</p>
<h2>7. Reporting, restrictions and complaints</h2><p>Test accounts are active. Public report handling, appeals and complaints contacts are not operational in this preview. They must be staffed and tested before public launch. In the live service, proportionate restrictions, reasons where appropriate, evidence preservation and an appeal process are required for suspected abuse.</p>
<h2>8. Changes and account closure</h2><p>The final service must record the terms version accepted at registration, notify users of material changes as appropriate, and provide account closure and data-rights routes. These account features are not active yet.</p>
<h2>Reference sources</h2><p><a href="https://www.legislation.gov.uk/ukpga/2015/15/section/62" target="_blank" rel="noopener noreferrer">Consumer Rights Act: fairness of terms</a> · <a href="https://www.legislation.gov.uk/ukpga/2015/15/section/65" target="_blank" rel="noopener noreferrer">Limits on excluding negligence liability</a> · <a href="https://www.fca.org.uk/publication/finalised-guidance/fg24-1.pdf" target="_blank" rel="noopener noreferrer">FCA financial promotions guidance</a></p>`},
privacy:{title:'Privacy & browser storage',intro:'Current preview information + pre-launch requirements · version 0.1',body:`
<h2>Test accounts and member posts</h2><p>Account credentials, saved profiles, member posts, likes and comments are processed by the connected Supabase service. Saved profile details remain accessible only to their account owner. Publishing a member post shares its text, your display name and username with signed-in members. These author details are recorded when you publish. Member comments share their text, your display name and username with signed-in members. Likes are associated with your account. You can remove your own likes and delete your own posts and comments. Clearing preview data does not delete your saved account or member posts.</p><h2>What the sample preview stores</h2><p>Sample profile edits, posts, follows, saved items, messages, proposals and introduction drafts are stored using sessionStorage in your browser. These sample actions are not sent to other people. The separate signed-in member feed and saved account forms do send data to the backend as described above. This browser storage is not end-to-end encrypted or a secure document vault. Do not enter real personal, financial or confidential information.</p><p>Data lasts for the browser page session and may survive reloads or a browser’s session-restore feature. Use the button below to clear it explicitly. Do not use shared devices for sensitive information.</p><button data-action="reset">Clear preview data</button>
<h2>Hosting and technical requests</h2><p>Render hosts the site over HTTPS. Loading the site sends ordinary connection information, such as your IP address and browser request information, to the hosting service. We have not added advertising trackers, analytics tools, third-party fonts or payment widgets to this preview. Provider-level logging and retention must be documented before public launch; we do not claim that visiting a hosted site produces no logs.</p><p><a href="https://render.com/privacy" target="_blank" rel="noopener noreferrer">Render privacy policy</a></p>
<h2>Who controls the service</h2><p>The operator’s legal identity, contact address and privacy contact are not yet confirmed. Public signup, identity verification and live proposal sharing remain closed. These details must be supplied in the final privacy notice before public registration or identity verification opens.</p>
<h2>Before live accounts open</h2><p>The final notice must specify each purpose and lawful basis, data categories, recipients and providers, international transfer safeguards where required, retention periods, data rights and the complaints route. Identity evidence must go through an approved verification process with restricted access and an appropriate retention schedule. Do not send identity documents through this preview.</p><p>Marketing must be optional where required. Verification information must not be reused for advertising. Automated checks and any materially significant decisions must be explained with an appropriate human review route.</p>
<h2>Your information and rights</h2><p>Use the clear-data control for preview content held in this session. Before a live service launches, access, correction, deletion, objection, restriction and portability requests must have a functioning contact route, as applicable under relevant law. UK users may also raise concerns with the Information Commissioner’s Office.</p><p><a href="https://ico.org.uk/for-the-public/" target="_blank" rel="noopener noreferrer">ICO information for the public</a> · <a href="https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/individual-rights/the-right-to-be-informed/what-privacy-information-should-we-provide/" target="_blank" rel="noopener noreferrer">Privacy notice requirements</a></p>`},
investor:{title:'Investor verification policy',intro:'Pre-launch policy · investor approval is not active in the preview',body:`
<h2>An investor role must be earned</h2><p>Choosing “investor” in a profile, verifying an email address or passing a bot check must not grant an approved investor role. The sample directory contains fictional profiles only. No one has been verified through this preview.</p>
<h2>Checks required before approval</h2><ol><li><b>Account protection:</b> verified email, server-validated bot checks, multi-factor authentication and abuse monitoring.</li><li><b>Identity:</b> a suitable identity and liveness process, subject to the relevant privacy requirements and a review route for genuine users who cannot complete automated checks.</li><li><b>Organisation and authority:</b> where a firm is represented, confirm its existence, the applicant’s role and authority using independent sources and contact details. Company registration alone does not prove legitimacy or financial capacity.</li><li><b>Investor claims:</b> review the stated investment role, relevant experience, sector and stage. Request proportionate supporting evidence through a secure process. A profile must not imply a guarantee of available funds.</li><li><b>Regulatory and fraud checks:</b> check claimed authorisations and relevant permissions with the appropriate regulator where the proposed activity requires them. Check official warnings and clone-firm indicators, and confirm contact details independently. Not every person investing their own money is required to appear on the FCA Register.</li><li><b>Human decision:</b> a reviewer records the evidence categories, outcome, reasons and review date. Material conflicts and unverified claims require resolution before approval.</li></ol>
<h2>What the badge means</h2><p>Future labels must say exactly what was checked, by whom and when: for example identity checked or organisation role checked. They must not imply FCA approval, investment advice, suitability, guaranteed capital, guaranteed returns or permanent safety. Users must be able to view the scope and age of a check.</p>
<h2>Technical access controls</h2><p>Investor permissions must be issued by the server from trusted review records, never from user-editable profile metadata. Approval, expiration, suspension and revocation must be enforced on every protected request. Sensitive actions must require a sufficiently strong authenticated session.</p><p>Proposals must be private by default and shared only with the founder’s chosen recipient after an explicit confirmation. Authorisation must be enforced on the server; drafts and attachments must not become publicly searchable. Withdrawal, recipient access and retention limits must be clear. No attachment upload is enabled in this preview.</p>
<h2>Continuing checks and abuse response</h2><p>Approval must have an expiry and a re-review process. Reports, identity or organisation changes, new risk evidence and account compromise must trigger review or proportionate suspension. Record reviewer actions, prevent users approving themselves, and provide an appeal route.</p><p>Impersonation, falsified evidence, demands for upfront “release of funding” fees and misleading guarantees are prohibited. Live reporting, blocking and incident response must be operational before introductions are enabled.</p>
<h2>Legal review before live introductions</h2><p>The operator must assess the regulatory scope of investor matching, proposal distribution, financial promotions, commissions and any transaction features. A networking disclaimer alone does not make those activities unregulated. Live proposal delivery remains unavailable until that assessment and the required controls are complete.</p><p><a href="https://www.fca.org.uk/consumers/how-check-firm-individual-authorised" target="_blank" rel="noopener noreferrer">FCA: check a firm or individual</a> · <a href="https://www.fca.org.uk/consumers/protect-yourself-scams" target="_blank" rel="noopener noreferrer">FCA: protect yourself from scams</a></p>`},
community:{title:'Community & safety policy',intro:'Pre-launch rules · sample content only in the current preview',body:`
<h2>Be honest about who you are</h2><p>Do not impersonate people or organisations, misrepresent professional credentials, forge verification evidence or fabricate investment experience. Clearly disclose paid promotion and relevant commercial conflicts.</p>
<h2>Keep networking safe</h2><p>Scams, harassment, threats, discrimination, doxxing, malware, unsolicited bulk messages and exploitation are prohibited. Do not request passwords, recovery codes or private account keys. Respect another person’s decision not to connect.</p>
<h2>Respect confidential information</h2><p>Do not publish another person’s proposal, contact details, private messages or identity evidence without appropriate permission. Share only content you have the right to share. Do not offer or solicit unlawful insider information or market manipulation.</p>
<h2>Investment and business claims</h2><p>No guaranteed returns, fake funding commitments, concealed fees or misleading regulatory claims. Verification is not an endorsement of a proposal or a guarantee of safety. Investment promotions and transactions remain unavailable pending the required legal and compliance review.</p>
<h2>Moderation before launch</h2><p>The live service needs working reporting, blocking, evidence preservation, proportionate enforcement, notifications where appropriate and appeals. The current report dialog is a demonstration only and sends no report. Public interaction remains closed until these workflows and responsible contacts are in place.</p>`}
};
function policyLinks(){return `<nav class="policyLinks" aria-label="Policies"><a href="#terms">Terms & conditions</a><a href="#privacy">Privacy</a><a href="#investor-policy">Investor verification</a><a href="#community-policy">Community rules</a><a href="#security">Security</a></nav>`}
function policyPage(which){const d=policyDocuments[which];return `<div class="sectionHead"><div class="eyebrow">VIRTLINK · TRUST & RESPONSIBILITY</div><h1>${d.title}</h1><p>${d.intro}</p></div><div class="notice">Draft for review. Legal operator details and launch controls are incomplete. This is not a claim that the live platform or investor checks are operational.</div><article class="panel pad policyContent">${d.body}</article>${policyLinks()}`}
