"""Browser regression checks for the isolated concept preview."""
import functools, http.server, pathlib, threading, unittest
from playwright.sync_api import sync_playwright
ROOT=pathlib.Path(__file__).resolve().parent
class PreviewTests(unittest.TestCase):
 @classmethod
 def setUpClass(cls):
  cls.http=http.server.ThreadingHTTPServer(('127.0.0.1',0),functools.partial(http.server.SimpleHTTPRequestHandler,directory=str(ROOT/'dist')))
  threading.Thread(target=cls.http.serve_forever,daemon=True).start()
  cls.pw=sync_playwright().start();cls.browser=cls.pw.chromium.launch()
  cls.url=f'http://127.0.0.1:{cls.http.server_port}/'
 @classmethod
 def tearDownClass(cls):
  cls.browser.close();cls.pw.stop();cls.http.shutdown();cls.http.server_close()
 def test_account_gate(self):
  page=self.browser.new_page(viewport={'width':390,'height':844});errors=[];auth_requests=[]
  page.on('pageerror',lambda e:errors.append(str(e)))
  page.route('https://challenges.cloudflare.com/**',lambda route:route.fulfill(content_type='text/javascript',body='window.turnstile={render:()=>1,reset:()=>{}};'))
  page.route('https://hnoqhdqnvvndyipcoudi.supabase.co/**',lambda route:(auth_requests.append(route.request.url),route.abort()))
  page.goto(self.url+'accounts.html')
  page.get_by_text('Sign in with your existing test account.',exact=True).wait_for()
  self.assertFalse(page.locator('#profilePanel').is_visible())
  self.assertFalse(page.locator('#mfaPanel').is_visible())
  page.get_by_label('Email (required)',exact=True).fill('test@example.invalid')
  page.get_by_label('Password (required)',exact=True).fill('NotARealPassword')
  page.get_by_role('button',name='Sign in securely',exact=True).click()
  page.get_by_text('Complete the human check first.',exact=True).wait_for()
  self.assertEqual(page.get_by_label('Password (required)',exact=True).input_value(),'')
  self.assertEqual(auth_requests,[])
  self.assertFalse(page.evaluate('document.documentElement.scrollWidth > innerWidth'))
  self.assertEqual(errors,[])
  page.screenshot(path=str(ROOT/'accounts-mobile-preview.png'),full_page=True)
  page.close()
 def test_connected_profile(self):
  page=self.browser.new_page();errors=[]
  page.on('pageerror',lambda e:errors.append(str(e)))
  # Exercise main-page identity rendering independently of real credentials.
  page.route('**/account-main.js',lambda route:route.fulfill(content_type='text/javascript',body=''))
  page.goto(self.url+'#profile')
  row={'display_name':'Account <Example>','headline':'Engineer','profession':'Technology','location':'Example city','skills':'Coding, Design','looking_for':'Collaborators','bio':'Saved biography'}
  page.evaluate('(row)=>window.dispatchEvent(new CustomEvent("virtlink-account",{detail:row}))',row)
  self.assertTrue(page.get_by_role('heading',name='Account <Example>',exact=True).is_visible())
  self.assertTrue(page.get_by_text('Saved biography',exact=True).is_visible())
  self.assertEqual(page.locator('.loginButton').inner_text(),'Sign out')
  page.goto(self.url+'#feed')
  page.get_by_role('textbox',name='Write a post').fill('Test preview post')
  page.get_by_role('button',name='Post',exact=True).click()
  self.assertNotIn('Account <Example>',page.evaluate('sessionStorage.getItem("virtlink-preview-v1")'))
  page.evaluate('window.dispatchEvent(new CustomEvent("virtlink-account",{detail:null}))')
  self.assertEqual(page.locator('.loginButton').inner_text(),'Login')
  self.assertNotIn('Account <Example>',page.locator('#app').inner_text())
  self.assertEqual(errors,[]);page.close()
 def test_preview(self):
  page=self.browser.new_page(viewport={'width':1440,'height':1000});errors=[]
  page.on('pageerror',lambda e:errors.append(str(e)))
  page.goto(self.url)
  page.locator('.heroCity').wait_for()
  self.assertTrue(page.locator('.heroCity').evaluate('(i)=>i.complete && i.naturalWidth>0'))
  page.screenshot(path=str(ROOT/'welcome-preview.png'),full_page=True)
  page.get_by_role('button',name='Sign Up',exact=True).click()
  self.assertTrue(page.get_by_text('Public accounts are not open yet.',exact=False).is_visible())
  self.assertEqual(page.locator('input[type=password]').count(),0)
  page.get_by_role('button',name='Close dialog').click()
  for route in ['feed','network','jobs','communities','events','marketplace','messages','profile','saved','world','security','investors','terms','privacy','investor-policy','community-policy','menu']:
   page.goto(self.url+'#'+route)
   page.locator('main h1').wait_for()
   self.assertFalse(page.evaluate('document.documentElement.scrollWidth > innerWidth'),route)
   if route in ['feed','world','profile','jobs','messages']:
    page.screenshot(path=str(ROOT/(route+'-preview.png')),full_page=True)
  page.goto(self.url+'#feed')
  page.get_by_role('textbox',name='Write a post').fill('<img src=x onerror="alert(1)"> Preview post')
  page.get_by_role('button',name='Post',exact=True).click()
  self.assertTrue(page.get_by_text('<img src=x onerror="alert(1)"> Preview post',exact=True).is_visible())
  self.assertEqual(page.locator('.bodyText img').count(),0)
  page.locator('[data-action="save"]').first.click()
  page.goto(self.url+'#saved');self.assertEqual(page.locator('.post').count(),1)
  page.goto(self.url+'#network')
  page.locator('.peopleGrid').get_by_role('button',name='Follow Emma Taylor',exact=True).click()
  self.assertTrue(page.locator('.peopleGrid').get_by_role('button',name='Unfollow Emma Taylor',exact=True).is_visible())
  page.get_by_role('textbox',name='Filter people').fill('insurance')
  page.locator('#networkFilter').get_by_role('button',name='Search',exact=True).click()
  self.assertEqual(page.locator('.personCard').count(),1)
  page.locator('#globalSearch').fill('developer');page.locator('#searchForm').evaluate('(f)=>f.requestSubmit()')
  self.assertTrue(page.get_by_role('heading',name='Search results').is_visible())
  self.assertTrue(page.get_by_text('Emma Taylor',exact=True).first.is_visible())
  page.goto(self.url+'#profile');page.get_by_role('button',name='Edit profile',exact=True).click()
  page.get_by_role('textbox',name='Display name',exact=True).fill('Demo Person')
  page.get_by_role('button',name='Save preview profile').click()
  self.assertTrue(page.get_by_role('heading',name='Demo Person',exact=True).is_visible())
  page.reload();self.assertTrue(page.get_by_role('heading',name='Demo Person',exact=True).is_visible())
  page.goto(self.url+'#messages');page.get_by_role('textbox',name='Write a sample message').fill('Sample, not delivered')
  page.get_by_role('button',name='Save sample message').click()
  self.assertTrue(page.get_by_text('Sample, not delivered',exact=True).is_visible())
  page.goto(self.url+'#world');page.get_by_role('button',name='Jobs Hub',exact=True).click()
  self.assertTrue(page.get_by_role('link',name='Explore opportunities').is_visible())
  page.goto(self.url+'#investors')
  self.assertEqual(page.locator('.investorCard').count(),4)
  page.get_by_label('Investor sector',exact=True).select_option('Healthcare')
  page.get_by_role('button',name='Filter investors',exact=True).click()
  self.assertEqual(page.locator('.investorCard').count(),1)
  page.get_by_role('button',name='Create proposal',exact=True).click()
  page.get_by_label('Business name',exact=True).fill('Example Venture')
  page.get_by_label('One-line pitch',exact=True).fill('Useful software for independent businesses')
  page.get_by_label('Problem and solution',exact=True).fill('Small businesses need clearer tools. This is a fictional proposal for testing.')
  page.get_by_label('Progress so far',exact=True).fill('Sample idea-stage research.')
  page.get_by_label('Team and relevant experience',exact=True).fill('Example founding team.')
  page.get_by_label('Funding sought',exact=True).fill('100000')
  page.get_by_label('How would you use the funding?',exact=True).fill('Build and test the first prototype.')
  page.get_by_role('button',name='Save proposal draft',exact=True).click()
  self.assertTrue(page.get_by_role('heading',name='Example Venture',exact=True).is_visible())
  page.get_by_role('button',name='Find investors',exact=True).first.click()
  page.get_by_role('button',name='View investor',exact=False).first.click()
  page.get_by_role('button',name='Prepare an introduction',exact=True).click()
  page.get_by_label('Your introduction',exact=True).fill('I would like to discuss this fictional business proposal with you.')
  page.get_by_role('button',name='Review introduction',exact=True).click()
  page.get_by_role('button',name='Save introduction draft',exact=True).click()
  self.assertTrue(page.get_by_text('Preview draft · not sent',exact=True).is_visible())
  page.reload();self.assertTrue(page.get_by_role('button',name='Introductions (1)',exact=True).is_visible())
  page.get_by_role('button',name='My proposals (1)',exact=True).click()
  page.get_by_role('button',name='Delete draft',exact=True).click()
  page.get_by_role('button',name='Delete proposal',exact=True).click()
  self.assertTrue(page.get_by_role('button',name='Introductions (0)',exact=True).is_visible())
  page.goto(self.url+'#terms');self.assertTrue(page.get_by_text('This draft does not create blanket immunity',exact=False).is_visible())
  page.goto(self.url+'#investor-policy');self.assertTrue(page.get_by_role('heading',name='An investor role must be earned',exact=True).is_visible())
  page.set_viewport_size({'width':390,'height':844})
  for route in ['welcome','feed','network','jobs','communities','events','marketplace','messages','profile','world','security','investors','terms','privacy','investor-policy','menu']:
   page.goto(self.url+'#'+route);page.locator('main h1').wait_for()
   self.assertFalse(page.evaluate('document.documentElement.scrollWidth > innerWidth'),route+' mobile overflow')
   if route in ['welcome','feed','world','profile','investors']:
    page.screenshot(path=str(ROOT/(route+'-mobile-preview.png')),full_page=True)
  self.assertEqual(errors,[])
  page.close()
if __name__=='__main__':unittest.main()
